### ISSUE TITLE
Emojis inside a Text Box or TextArea ?

### ISSUE THREAD

**Issue by MiguelRyR** [hlaueriksson/GEmojiSharp#1]
How can I use Emojis inside a Text Box or Input Box

Example:
<textarea> :earth_africa: </textarea>
<input type="text" name="txtEmoji" value=":earth_africa:"><br>

This is not  working since the emoji will be replaced by the "_g-emoji class="g-emoji" alias="earth_africa" fallback-src="https://github.githubassets.com/images/icons/emoji/ : .._.":

![Emo](https://user-images.githubusercontent.com/19353119/59206190-6f383d00-8b72-11e9-86f5-f830fad375c9.png)

**Comment by hlaueriksson** [comment]
Thanks for the feedback. This has been fixed in `1.1.0`;
https://www.nuget.org/packages/GEmojiSharp.TagHelpers/1.1.0

Sample;
https://github.com/hlaueriksson/GEmojiSharp/blob/master/samples/GEmojiSharp.Sample.Web/Pages/Component.cshtml#L26
