### ISSUE TITLE
some are missing in 1.4.0

### ISSUE THREAD

**Issue by SbiCA** [hlaueriksson/GEmojiSharp#10]
I'm maybe mistaking or this list (https://github.com/hlaueriksson/github-emoji) is outdated but I was not able to find the following emojis that are in the list in version 1.4.0
- `:magic_wand:` 
- `:rock:`
- `:roller_skate:`

here is s small repro
``` csharp
var wand = Emoji.Raw(":magic_wand:"); // 🪄
WriteLine($"wand: {wand}");
var roller = Emoji.Find(":roller_skate:").FirstOrDefault(); // 🛼
WriteLine($"roller: {roller?.Raw}");
var rock = Emoji.Find("rock").FirstOrDefault(); // 🪨
WriteLine($"rock: {rock?.Raw}");

var thisIsDefined = Emoji.Find("horse").FirstOrDefault();
WriteLine($"horse: {thisIsDefined?.Raw}");
```

Cheers

**Comment by SbiCA** [comment]
this is the output on my end

```
wand: 
roller: 
rock: 👨‍🎤
horse: 🏇

```

**Comment by hlaueriksson** [comment]
Thanks for the feedback!

I have updated [hlaueriksson/github-emoji](https://github.com/hlaueriksson/github-emoji) with the latest versions of GitHub Emoji from [emoji.json](https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json) and [emojis](https://api.github.com/emojis).

Diff: https://github.com/hlaueriksson/github-emoji/commit/a2d0ca950ef930d1ebb251f74e2b3213cfdd0ef2

The three emoji (`:magic_wand:`, `:rock:` and `:roller_skate:`) are not displayed correctly on my machine (Windows 10).

I will bump `GEmojiSharp` to `1.5.0` in a while...

**Comment by hlaueriksson** [comment]
@SbiCA version `1.5.0` is released: https://www.nuget.org/packages/GEmojiSharp/1.5.0

**Comment by SbiCA** [comment]
Thanks for the quick update! I was able to test and all seems fine now 🎉
