### ISSUE TITLE
unEmoji

### ISSUE THREAD

**Issue by cbrandsma-cs** [hlaueriksson/GEmojiSharp#13]
Hi, 

I like the ability to go from text to an emoji, but can you also do the reverse?  (I have a few 3rd party integrations that blow up when they encounter an emoji, but I'd like to keep the meaning around.

**Comment by hlaueriksson** [comment]
Yes, that's a great idea!
An inverted version of `Emoji.Emojify`.
Let's call it `Demojify`, as the prefix [de-](https://www.macmillandictionary.com/dictionary/british/de) can be used to give a word the opposite meaning.

What do you think about this API?

```cs
Emoji.Demojify("🎉 initial commit"); // :tada: initial commit
"🎉 initial commit".Demojify(); // :tada: initial commit
```

**Comment by hlaueriksson** [comment]
Hi @cbrandsma-cs 

With the release of `GEmojiSharp` `2.0.0`, this is now supported:

- https://www.nuget.org/packages/GEmojiSharp/2.0.0

You can find examples in the unit test:

- [Documentation.cs](https://github.com/hlaueriksson/GEmojiSharp/blob/master/tests/GEmojiSharp.Tests/Documentation.cs#L18)
