### ISSUE TITLE
GemojsSharp v2.0.0 not show symbols in visual studio 17.3.2(build 24) in Console.WriteLine

### ISSUE THREAD

**Issue by gh250100** [hlaueriksson/GEmojiSharp#19]
hello ,

visual studio version 17.3.2(build 24)(on Mac)

emoji symbol not show in build output but in debug its fine .

build output:
Console.WriteLine shows (??=)
<img width="34" alt="image" src="https://user-images.githubusercontent.com/67205688/186589041-91ec2fc5-9add-4adb-9ec0-da5573094b00.png">

in debug mode:
when hovering on the variable symbol are fine 

<img width="429" alt="image" src="https://user-images.githubusercontent.com/67205688/186588855-1ff3e3b2-2f9b-4143-96cd-85e40d04ceb8.png">

thanks in advance

**Comment by hlaueriksson** [comment]
You need to set the correct output encoding.
An example from the `GEmojiSharp.DotnetTool`:

https://github.com/hlaueriksson/GEmojiSharp/blob/c7ddef7b102b9634c826d21d385471425bc14200/src/GEmojiSharp.DotnetTool/Program.cs#L6

**Comment by gh250100** [comment]
> You need to set the correct output encoding. An example from the `GEmojiSharp.DotnetTool`:
> 
> https://github.com/hlaueriksson/GEmojiSharp/blob/c7ddef7b102b9634c826d21d385471425bc14200/src/GEmojiSharp.DotnetTool/Program.cs#L6

thanks for replaying , I tried it but it didn't work , everything works fine for me until VISUAL STUDIO got update , when I run the same thing in VISUAL CODE its show the symbol fine

**Comment by hlaueriksson** [comment]
Is is the [integrated terminal](https://docs.microsoft.com/en-us/visualstudio/mac/integrated-terminal?view=vsmac-2022) in Visual Studio for Mac that is broken?

What happens if you `dotnet run` your project in the MacOS Terminal?

**Comment by gh250100** [comment]
> Is is the [integrated terminal](https://docs.microsoft.com/en-us/visualstudio/mac/integrated-terminal?view=vsmac-2022) in Visual Studio for Mac that is broken?
> 
> What happens if you `dotnet run` your project in the MacOS Terminal?

yes its look like the integrated terminal in Visual Studio on Mac is broken on that version ,
<img width="89" alt="image" src="https://user-images.githubusercontent.com/67205688/186766960-6f1af7cf-5a33-4c8a-a99d-3df91022ca29.png">

when run it from terminal in Mac with dotnet run it works fine

**Comment by hlaueriksson** [comment]
Maybe you can get it fixed by [reporting a bug](https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2022) to the Visual Studio for Mac team.
