### ISSUE TITLE
Skin Tones not supported

### ISSUE THREAD

**Issue by ultimaustin** [hlaueriksson/GEmojiSharp#3]
It looks like the Emoji.Emojify method doesn't support skin tones.

Passing "smiley" wrapped in colons to this method returns the unicode character for a smiley as expected.

However, passing the string "smiley" wrapped in quotes with ":skin-tone-6:" appended to it returns 😃:skin-tone-6: (i.e. Smiley unicode character + ":skin-tone-6")

Am I doing something wrong or are skin tones not supported in the current version?

N.B. Please forgive the weird syntax in this issue. When I try to write the strings as they are used, github is converting the colon syntax to emojis which makes it difficult to describe the issue. Hopefully, the above is clear.

**Comment by hlaueriksson** [comment]
Hi!

Thanks for your feedback!

This feature is not supported. Not yet, anyway.

I would like to keep the functionality the same way GitHub renders emoji.
Skin tones is not supported by GitHub yet.

As you have noted, comments like this:
```:smiley::skin-tone-6:```

Will render like this:
:smiley::skin-tone-6:

I will wait and see what GitHub will do with this in the future:
https://github.com/github/gemoji/pull/165
