### ISSUE TITLE
Color emojis in PowerToys Run

### ISSUE THREAD

**Issue by stamminator** [hlaueriksson/GEmojiSharp#32]
The emojis in the PowerToys Run plugin look like they're being drawn rather than the glyph itself being displayed, resulting in a monochrome outline rather than an accurate depiction on the emoji.

![powertoys run gemoji](https://github.com/user-attachments/assets/56da41b8-8868-42bc-99cd-d887d5aaf30a)

Is there any way to display the emoji "as-is" in full color?

**Comment by hlaueriksson** [comment]
PowerToys Run is a WPF app, and [TextBlock](https://github.com/microsoft/PowerToys/blob/808e6220bca9607b2e8632dc02aedd70d3ab12db/src/modules/launcher/PowerLauncher/ResultList.xaml#L113) that is used to render the result does not support emoji.

There is an issue here; https://github.com/dotnet/wpf/issues/91

You can create an [issue](https://github.com/microsoft/PowerToys/issues) in the PowerToys repo and ask them to change the `System.Windows.Controls.TextBlock` to `Emoji.Wpf.TextBlock`.
See https://github.com/samhocevar/emoji.wpf
