### ISSUE TITLE
blazor webassembly = erro

### ISSUE THREAD

**Issue by drma-tech** [hlaueriksson/GEmojiSharp#9]
I didn't see anything in the documentation about something to register the dll in program.cs so that these files can be recognized

```
GET https://localhost:5001/_content/GEmojiSharp.Blazor/style.css net::ERR_ABORTED 404
GET https://localhost:5001/_content/GEmojiSharp.Blazor/script.js net::ERR_ABORTED 404
```

![image](https://user-images.githubusercontent.com/12803050/108392606-a5580c00-71f1-11eb-932c-2f0628b63c88.png)

**Comment by hlaueriksson** [comment]
Hi @drma-dev 

Update `wwwroot/index.html` and add these two lines:

```
<link href="_content/GEmojiSharp.Blazor/style.css" rel="stylesheet" />
```

```
<script src="_content/GEmojiSharp.Blazor/script.js"></script>
```

It is briefly mentioned in the [README](https://github.com/hlaueriksson/GEmojiSharp#gemojisharpblazor-), but I should clarify the documentation.

You can take a look at [line 12](https://github.com/hlaueriksson/GEmojiSharp/blob/master/samples/GEmojiSharp.Sample.BlazorWebAssembly/wwwroot/index.html#L12) and [line 47](https://github.com/hlaueriksson/GEmojiSharp/blob/master/samples/GEmojiSharp.Sample.BlazorWebAssembly/wwwroot/index.html#L47) of a sample `index.html`.

**Comment by drma-tech** [comment]
I did it and that's exactly why this error is happening (he tries to look for something that doesn't exist).
You must have the reference in program.cs

**Comment by hlaueriksson** [comment]
Right. I think you need to import the `GEmojiSharp.Blazor` namespace in the `_Imports.razor` file.

Check out the [sample](https://github.com/hlaueriksson/GEmojiSharp/blob/master/samples/GEmojiSharp.Sample.BlazorWebAssembly/_Imports.razor#L11) file at line 11.

**Comment by drma-tech** [comment]
References in _import.razor only allow the use of components within razor pages.

To recognize the js and css files (of any component) you need to create these references within program.cs (or startup.cs, depending on the type of project).

It would have to have a code something like this:
`Services.AddGEmoji();`
This tells the project that there are static files that need to be read at startup.

**Comment by hlaueriksson** [comment]
I don't know how to reproduce this.

Are you able to run the [sample app](https://github.com/hlaueriksson/GEmojiSharp/tree/master/samples/GEmojiSharp.Sample.BlazorWebAssembly)?
